### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by arkinrc** [IRMVLab/EfficientLO-Net#1]
Hello !
First of all, really appreciate nice efforts and thanks to opensource this code. 
i encountered an issue while training the kitti odometry dataset. i follow the instructions as mentioned in README. error is given below,

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FusedConvRandomK' used by node sa1/layer0/FusedConvRandomK (defined at <string>:122) with these attrs: [flag_copy=0, kernel_size_W=15, kernel_size_H=9, distance=0.5, W=1800, npoints=3600, H=64, K=32, stride_w=1, stride_h=1]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

	 [[node sa1/layer0/FusedConvRandomK (defined at <string>:122) ]]

i am using Nvidia RTX3090 and cuda 11.4 and other all requirements are fulfilled. I have modified cuda version in fused_conv.sh of both folders and compiled as well. 
Could you please assist me to solve this issue @XINRUII 

Regards
Arkin

**Comment by XINRUII** [comment]
When creating the pretrained model, our version of CUDA is 9.0, so it may not be able to properly value the pretrained model in other CUDA environments. You can try deleting the line of "checkpoint_path" in comman_train.sh. Or set --checkpoint_path to None.

**Comment by arkinrc** [comment]
> 

Thanks for prompt feedback. I have tried both ways you told but at the end same error which i mentioned first. 

Regards
Arkin

**Comment by XINRUII** [comment]
We are sorry for this error, because  the first released code is based on TensorFlow, maybe we did not do a good job in the compatibility of environment and operator, we will open source the code based on PyTorch soon, this problem should be solved.

**Comment by arkinrc** [comment]
looking forward for the pytorch version... thank you so much again.
